// Weather data is now loaded lazily from /weather/*.json files at runtime.
// Generated by: node scripts/generate-weather-data.mjs
// Source: Open-Meteo Historical Weather API (archive-api.open-meteo.com)
//
// Each city has an individual JSON file in public/weather/{city-slug}.json
// containing all 4 seasons (spring, summer, autumn, winter).
// Southern-hemisphere cities have inverted season-to-date mappings so
// "summer" always means local summer.
